name: build holochain
on:
  workflow_dispatch:

jobs:
  build-holochain:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - system: x86_64-darwin
            runs-on: macos-latest
          - system: x86_64-darwin
            runs-on: multi-arch
          - system: aarch64-darwin
            runs-on: multi-arch
          - system: x86_64-linux
            runs-on: ubuntu-latest
        nixCommand:
          - "nix build .#holochain .#holochain-tests-fmt .#holochain-tests-clippy --no-link"
          - "nix build .#holochain-tests-nextest --no-link"
          - "nix build .#holochain-tests-wasm --no-link"

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: false

      - name: Install nix
        uses: cachix/install-nix-action@v18
        if: ${{ matrix.platform.runs-on != 'multi-arch' }}
        with:
          install_url: https://releases.nixos.org/nix/nix-2.12.0/install
          extra_nix_config: |
            experimental-features = flakes nix-command impure-derivations
            extra-experimental-features = impure-derivations ca-derivations
            sandbox = relaxed

      - name: Setup cachix
        uses: cachix/cachix-action@v12
        continue-on-error: ${{ matrix.platform.runs-on == 'multi-arch' }}
        with:
          name: holochain-ci
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Test comand ${{ matrix.nixCommand }}"
        run: ${{ matrix.nixCommand }} -L --show-trace --system ${{ matrix.platform.system }} --extra-experimental-features "ca-derivations impure-derivations"
