on:
  workflow_call:
    inputs:
      dry_run:
        type: string
        required: true
      debug:
        type: string
        required: true
      skip_prepare_logic:
        type: string
        required: true

      HOLOCHAIN_SOURCE_BRANCH:
        type: string
        required: true
      HOLOCHAIN_TARGET_BRANCH:
        type: string
        required: true
      HOLOCHAIN_URL:
        type: string
        required: false
        default: "https://github.com/holochain/holochain"
      HOLOCHAIN_NIXPKGS_URL:
        type: string
        required: false
        default: "https://github.com/holochain/holochain-nixkpgs.git"
      HOLONIX_URL:
        type: string
        required: false
        default: "https://github.com/holochain/holonix.git"
      HOLOCHAIN_REPO:
        type: string
        required: true
      CACHIX_REV:
        type: string
        required: true
    secrets:
      HRA_GITHUB_TOKEN:
        required: true
      CACHIX_SIGNING_KEY:
        required: true
      CACHIX_AUTH_TOKEN:
        required: true

    outputs:
      releasable_crates:
        description: "whether there are any releaseable crates"
        value: ${{ jobs.prepare.outputs.releasable_crates }}
      version:
        description: "which holochain version, if one, will be released"
        value: ${{ jobs.prepare.outputs.version }}
      tag:
        description: "which holochain tag, if one, will be released"
        value: ${{ jobs.prepare.outputs.tag }}
      nix_store_holochain_repo:
        description: "the store path containing the holochain repo"
        value: ${{ jobs.prepare.outputs.nix_store_holochain_repo }}
      nix_store_release_sh:
        description: "the store path containing the release.sh"
        value: ${{ jobs.prepare.outputs.nix_store_release_sh }}

jobs:
  prepare:
    env:
      HOLOCHAIN_REPO: ${{ inputs.HOLOCHAIN_REPO }}
      CACHIX_REV: ${{ inputs.CACHIX_REV }}
      HOLOCHAIN_SOURCE_BRANCH: ${{ inputs.HOLOCHAIN_SOURCE_BRANCH }}
      HOLOCHAIN_TARGET_BRANCH: ${{ inputs.HOLOCHAIN_TARGET_BRANCH }}
      HOLOCHAIN_URL: ${{ inputs.HOLOCHAIN_URL }}
      HOLOCHAIN_NIXPKGS_URL: ${{ inputs.HOLOCHAIN_NIXPKGS_URL }}
      HOLONIX_URL: "https://github.com/holochain/holonix.git"
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.write-env-and-tag.outputs.tag }}
      version: ${{ steps.write-env-and-tag.outputs.version }}
      version_compat: ${{ steps.write-env-and-tag.outputs.version_compat }}
      release_branch: ${{ steps.write-env-and-tag.outputs.release_branch }}
      releasable_crates: ${{ steps.bump-versions.outputs.releasable_crates }}
      nix_store_holochain_repo: ${{ steps.cache.outputs.nix_store_holochain_repo }}
      nix_store_release_sh: ${{ steps.cache.outputs.nix_store_release_sh }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Extend space
        uses: ./.github/actions/extend-space
        if: ${{ inputs.skip_prepare_logic != 'true' }}

      - name: Install nix
        uses: cachix/install-nix-action@v17
      - name: Setup cachix
        uses: cachix/cachix-action@v11
        continue-on-error: ${{ github.event_name != 'pull_request' }}
        with:
          name: holochain-ci
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          installCommand: |
            nix-env -if https://github.com/cachix/cachix/tarball/${CACHIX_REV:?} \
              --substituters 'https://cache.nixos.org https://cachix.cachix.org' \
              --trusted-public-keys 'cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY='
      - name: Set NIX_PATH (FIXME)
        run: echo NIX_PATH=nixpkgs=$(./scripts/nix_path.sh) >> $GITHUB_ENV

      - name: Restore the holochain release repository
        uses: steveeJ-forks/actions-cache/restore@retry
        with:
          path: |
            # asterisk is a workaround for https://github.com/actions/cache/issues/494
            /var/tmp/holochain_repo/*
            !/var/tmp/holochain_repo/.cargo/
            !/var/tmp/holochain_repo/target/
          key: holochain-repo-finalize-release-
          restore-keys: |
            holochain-repo-
          required: false

      - name: Restore holochain cargo related state and build files
        if: ${{ inputs.skip_prepare_logic != 'true' }}
        uses: steveeJ-forks/actions-cache/restore@retry
        id: restore-build-files
        with:
          path: |
            /var/tmp/holochain_repo/.cargo/bin/
            /var/tmp/holochain_repo/.cargo/registry/index/
            /var/tmp/holochain_repo/.cargo/registry/cache/
            /var/tmp/holochain_repo/.cargo/git/db/
            /var/tmp/holochain_repo/target/
          key: ${{ runner.os }}-prepare-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-prepare
            ${{ runner.os }}-test-release-cargo-test-standard
            ${{ runner.os }}
          required: false

      - name: Prepare the holochain repository
        env:
          HRA_GITHUB_TOKEN: ${{ secrets.HRA_GITHUB_TOKEN }}
        run: |
          set -exE -o pipefail

          if [[ ! -d "${HOLOCHAIN_REPO}" ]]; then
            rm -rf "${HOLOCHAIN_REPO}"
            mkdir -p "${HOLOCHAIN_REPO}"
          fi

          cd "${HOLOCHAIN_REPO}"

          if ! git status; then
            git init
            git remote add origin "${HOLOCHAIN_URL}"
          fi

          # use our custom token for more permissions, e.g. "workflow" which is needed to push workflow files
          git config --local "http.https://github.com/.extraheader" "AUTHORIZATION: basic $(echo -n pat:${HRA_GITHUB_TOKEN} | base64)"

          git fetch --all --tags --prune --prune-tags --force
          git branch --list --all
          git checkout --force -B ${HOLOCHAIN_SOURCE_BRANCH} remotes/origin/${HOLOCHAIN_SOURCE_BRANCH}

          # .gitignore might've changed
          git reset --hard
          git clean -fd

          obsolete_branches="$(git branch --list | sed -E 's/^ +//' | (grep -oE '^release-[0-9\.]+' || :))"
          if [[ -n "${obsolete_branches}" ]]; then
            git branch -D ${obsolete_branches}
          fi

      - name: Detect missing release headings
        if: ${{ inputs.skip_prepare_logic != 'true' }}
        run: |
          set -ex
          cd "${HOLOCHAIN_REPO}"

          nix-shell --argstr flavor release --pure --run '
            set -e

            release-automation \
              --workspace-path=$PWD \
              --log-level=debug \
              crate detect-missing-releaseheadings
            '

      - name: Generate crate READMEs from doc comments
        if: ${{ inputs.skip_prepare_logic != 'true' }}
        run: |
          cd "${HOLOCHAIN_REPO}"
          nix-shell --pure --argstr flavor release --run "./scripts/generate_readmes.sh"

      - name: Bump the crate versions for the release
        id: bump-versions
        if: ${{ inputs.skip_prepare_logic != 'true' }}
        run: |
          set -exu
          cd "${HOLOCHAIN_REPO}"

          nix-shell --argstr flavor release --pure --run '
            set -e
            cargo sweep -s

            release-automation \
              --workspace-path=$PWD \
              --log-level=debug \
              release \
                --force-branch-creation \
                --steps=CreateReleaseBranch

            release-automation \
              --workspace-path=$PWD \
              crate apply-dev-versions --commit --no-verify

            release-automation \
              --workspace-path=$PWD \
              --log-level=debug \
              --match-filter="^(holochain|holochain_cli|kitsune_p2p_proxy)$" \
              release \
                --no-verify-pre \
                --force-tag-creation \
                --additional-manifests="crates/test_utils/wasm/wasm_workspace/Cargo.toml" \
                --disallowed-version-reqs=">=0.2" \
                --steps=BumpReleaseVersions

            cargo sweep -f
            '

          if ! git diff --exit-code --quiet ${HOLOCHAIN_SOURCE_BRANCH}; then
            echo "::set-output name=releasable_crates::true"
          else
            echo "::set-output name=releasable_crates::false"
          fi

      - name: Run dmesg on error
        if: ${{ failure() }}
        run: sudo dmesg

      - name: Append to the environment file and set outputs
        id: write-env-and-tag
        run: |
          cd "${HOLOCHAIN_REPO}"
          RELEASE_BRANCH=$(git branch --show-current)

          echo "::set-output name=tag::${TAG}"
          echo "::set-output name=version::${VERSION}"
          echo "::set-output name=version_compat::${VERSION_COMPAT}"
          echo "::set-output name=release_branch::${RELEASE_BRANCH}"

      - name: Merge release branch to the target branch
        run: |
          set -exu
          cd "${HOLOCHAIN_REPO}"

          RELEASE_BRANCH="${{ steps.write-env-and-tag.outputs.release_branch }}""

          if ! (git branch --list --all | grep origin/${HOLOCHAIN_TARGET_BRANCH}); then
            git checkout -B ${HOLOCHAIN_TARGET_BRANCH} "${RELEASE_BRANCH}"
          else
            git checkout --force -B ${HOLOCHAIN_TARGET_BRANCH} origin/${HOLOCHAIN_TARGET_BRANCH}
            git merge --ff-only "${RELEASE_BRANCH}"
          fi

      - name: Cache the holochain release repository (nix)
        id: cache
        run: |
          export nix_store_holochain_repo=$(nix store add-path "$HOLOCHAIN_REPO")
          echo "nix_store_holochain_repo: $nix_store_holochain_repo"
          echo "::set-output name=nix_store_holochain_repo::$nix_store_holochain_repo"

      # - name: Cache the holochain release repository
      #   uses: steveeJ-forks/actions-cache/save@main
      #   with:
      #     path: |
      #       /var/tmp/holochain_release.sh
      #       # asterisk is a workaround for https://github.com/actions/cache/issues/494
      #       /var/tmp/holochain_repo/*
      #       !/var/tmp/holochain_repo/.cargo/
      #       !/var/tmp/holochain_repo/target/
      #     key: holochain-repo-${{ github.run_id }}-${{ github.run_number }}

      - name: Cache cargo related build files
        uses: steveeJ-forks/actions-cache/save@main
        if: ${{ inputs.skip_prepare_logic != 'true' }}
        with:
          path: |
            /var/tmp/holochain_repo/.cargo/bin/
            /var/tmp/holochain_repo/.cargo/registry/index/
            /var/tmp/holochain_repo/.cargo/registry/cache/
            /var/tmp/holochain_repo/.cargo/git/db/
            /var/tmp/holochain_repo/target/
          key: ${{ runner.os }}-prepare-${{ github.run_id }}-${{ github.run_number }}

      - name: Setup SSH session
        uses: steveeJ-forks/action-upterm@main
        if: ${{ failure() && inputs.debug == 'true' }}
        env:
          HRA_GITHUB_TOKEN: ${{ secrets.HRA_GITHUB_TOKEN }}
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: steveeJ,jost-s,freesig,neonphog,thedavidmeister,maackle
