on:
  push:
    branches:
      - "holochain.github.io"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test_setup:
    name: Test Holonix Setup
    runs-on: ubuntu-latest
    steps:
      - name: Call setup script
        run: bash <(curl https://holochain.github.io/holochain/setup.sh)
      - name: Test nix command
        run: $(which nix) run --version
