on:
  push:
    branches:
      - "holochain.github.io"

jobs:
  test_setup:
    name: Test Holonix Setup
    runs-on: ubuntu-latest
    steps:
      - name: Install nix
        uses: cachix/install-nix-action@v19
        with:
          nix_path: nixpkgs=channel:nixos-22.11

      - name: Call setup script
        run: sh <(curl https://holochain.github.io/holochain/setup.sh)

      - name: Setup tmate session if build and test run failed
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
