on:
  push:
    branches:
      - "holochain.github.io"

jobs:
  test_setup:
    name: Test Holonix Setup
    runs-on: ubuntu-latest
    steps:
      - name: Call setup script
        run: echo "hello"
